---
- hosts: back
  gather_facts: true
  become: true
 
  tasks:
  - name: Load mysql vars
    ansible.builtin.include_vars: mysql.yaml
    no_log: true

  - name: changement pwd mysql
    ansible.builtin.shell: /usr/bin/mysqladmin -u root -p{{ old_pass }} password '{{ new_pass }}'
    ignore_errors: yes
    no_log: yes
